- hosts: greens
  remote_user: ec2-user
  become: yes
  tasks:
    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest
    - name: start the service
      service:
        name: httpd
        state: started
        enabled: True
    - name: Copy file with owner and permissions
      copy:
        src:  index.html
        dest: /var/wwww/html/index.html
      
